fullnameOverride: "whereshans-api"

replicaCount: 1

containers:
  - name: api
    image: naesheim/whereshans_api
    tag: latest
    pullPolicy: Always
    environment:
        PERSISTENT_STORAGE: /tmp/database

    volumeMounts:
      - name: location-data
        mountPath: /tmp/database

    ports:
      - name: "my-port"
        containerPort: 5000
        protocol: TCP
    resources:
      limits:
        cpu: 400m
        memory: 248Mi
      requests:
        cpu: 100m
        memory: 128Mi

volumes:
  - name: location-data
    persistentVolumeClaim:
      claimName: location-vol 

services:
  - name: api
    type: ClusterIP
    port: 8080
    targetPort: 5000
    proto: TCP
    selector:
      app: whereshansel
      release: whereshansel-whereshansel

ingress:
  enabled: true
  hosts:
    - host: api.naesheim.com
      paths:
        - path: /
          serviceName: api
          servicePort: 8080
    
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"

  tls:
    - secretName: whereshans
      hosts:
        - api.naesheim.com
