version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout 
      - run:
          command: docker build -t hansel-api-$SHA

  test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run: 
          command: |
            docker container run -d -p 8000:5000 
            http_response=$(curl -i localhost:8080 | head -n 1 | cut -f 2 -d ' ')
            if [$http_response -ne 200]
              exit 0
            fi
  
  pushImage:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          command: |
            docker login -u $username --password-stdin $password
            docker push 

workflows:
  version: 2

  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - pushImage:
          requires:
            - test
