[certificates]
caCrt    = "gs://naesheim-home-terraform/keys/cluster_ca_certificate.crt"
caKey    = "gs://naesheim-home-terraform/keys/cluster_client_key.key"
caClient = "gs://naesheim-home-terraform/keys/client_certificate.crt"

[settings]
kubeContext = "k8s-gcloud"
username = "$CLUSTER_USERNAME"
password = "$CLUSTER_PASSWORD" 
clusterURI = "${ENDPOINT}"

# [helmRepos]
# local = "http://127.0.0.1:8879"

[namespaces.default]
    useTiller = true

# define the desired state of your applications helm charts
# each contains the following:

[apps]
    [apps.api]
    name = "whereshans-api"
    description = "hans api"
    namespace = "default"
    enabled = true
    chart = "../whereshans-api-0.1.0.tgz"
    version = "0.1.0"
    # [apps.api.set]
    # "containers[0].tag" = "${CIRCLE_SHA}"
